
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 9;
  public static final int POW = 35;
  public static final int STRING_LITERAL = 60;
  public static final int MULT = 33;
  public static final int CHAR = 6;
  public static final int LTEQ = 36;
  public static final int STR = 7;
  public static final int INTEGER = 56;
  public static final int SEMI = 51;
  public static final int LPAREN = 44;
  public static final int INT = 3;
  public static final int FOR = 16;
  public static final int MINUS = 32;
  public static final int CHARACTER = 59;
  public static final int RPAREN = 45;
  public static final int AND = 42;
  public static final int NOT = 40;
  public static final int LT = 38;
  public static final int RANGE = 18;
  public static final int RATIONAL = 57;
  public static final int ILLEGAL_CHARACTER = 54;
  public static final int EQUALTO = 41;
  public static final int OR = 43;
  public static final int TDEF = 12;
  public static final int COMMA = 52;
  public static final int BOOL = 2;
  public static final int THREAD = 21;
  public static final int DIV = 34;
  public static final int RAT = 4;
  public static final int PLUS = 31;
  public static final int MAIN = 11;
  public static final int IF = 25;
  public static final int DOT = 53;
  public static final int LSQB = 46;
  public static final int FLOATING = 58;
  public static final int WAIT = 22;
  public static final int OF = 17;
  public static final int BOOLEAN = 55;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int EQUAL = 30;
  public static final int error = 1;
  public static final int BREAK = 29;
  public static final int FDEF = 13;
  public static final int TOP = 8;
  public static final int COLON = 50;
  public static final int LBRACE = 48;
  public static final int DICT = 10;
  public static final int ELSE = 27;
  public static final int READ = 20;
  public static final int WHILE = 28;
  public static final int FLOAT = 5;
  public static final int RBRACE = 49;
  public static final int QUESTION = 15;
  public static final int ALIAS = 19;
  public static final int RSQB = 47;
  public static final int GT = 39;
  public static final int ELIF = 26;
  public static final int PRINT = 23;
  public static final int LENGTH = 14;
  public static final int NOTEQ = 37;
  public static final int IDENTIFIER = 61;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "INT",
  "RAT",
  "FLOAT",
  "CHAR",
  "STR",
  "TOP",
  "SEQ",
  "DICT",
  "MAIN",
  "TDEF",
  "FDEF",
  "LENGTH",
  "QUESTION",
  "FOR",
  "OF",
  "RANGE",
  "ALIAS",
  "READ",
  "THREAD",
  "WAIT",
  "PRINT",
  "RETURN",
  "IF",
  "ELIF",
  "ELSE",
  "WHILE",
  "BREAK",
  "EQUAL",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "POW",
  "LTEQ",
  "NOTEQ",
  "LT",
  "GT",
  "NOT",
  "EQUALTO",
  "AND",
  "OR",
  "LPAREN",
  "RPAREN",
  "LSQB",
  "RSQB",
  "LBRACE",
  "RBRACE",
  "COLON",
  "SEMI",
  "COMMA",
  "DOT",
  "ILLEGAL_CHARACTER",
  "BOOLEAN",
  "INTEGER",
  "RATIONAL",
  "FLOATING",
  "CHARACTER",
  "STRING_LITERAL",
  "IDENTIFIER"
  };
}

